### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by nekronos** [nekronos/gbc_rs#1]
## Timer
- [x] Add timer registers
- [x] Implement timer logic. Figure out how to deal with speed/frequency and cycle flushing
## Ppu
- [x] Implement cycle flush. Starting with just making sure scanline register is incremented at the correct speed.
- [x] Request interrupt for vblank
- [x] Figure out what LCD STAT interrupt is
